import { useRef, useState } from "react";
import html2pdf from "html2pdf.js";

function ReportDownload({
  result,
  atsScore,
  jobMatch,
  resumeHealth,
  contentScore,
  skillMatching,
  resumeHealthData,
  finalSummary,
}) {
  const reportRef = useRef(null);
  const [downloading, setDownloading] = useState(false);

  if (!result) {
    return null;
  }

  const safeSkillMatching =
    skillMatching || result?.skill_matching || {};

  const safeHealth =
    resumeHealthData ||
    result?.step_39_resume_health ||
    {};

  const safeSummary =
    finalSummary ||
    result?.step_40_analysis_summary ||
    {};

  const improvementPlan =
    result?.step_34_improvement_plan || {};

  const bulletAnalysis =
    result?.step_35_bullet_analysis || {};

  const achievementAnalysis =
    result?.step_36_achievement_analysis || {};

  const keywordAnalysis =
    result?.ats_keyword_analysis || {};

  const resumeQuality =
    result?.resume_quality || {};

  const sectionScores =
    result?.section_scores || {};

  const roleAlignment =
    result?.step_38_job_title_alignment ||
    result?.step_38_job_role_alignment ||
    {};

  const skillGaps =
    result?.skill_gaps || [];

  const matchedRequired =
    safeSkillMatching?.matched_required || [];

  const missingRequired =
    safeSkillMatching?.missing_required || [];

  const matchedPreferred =
    safeSkillMatching?.matched_preferred || [];

  const missingPreferred =
    safeSkillMatching?.missing_preferred || [];

  const matchedKeywords =
    keywordAnalysis?.matched_keywords || [];

  const missingKeywords =
    keywordAnalysis?.missing_keywords || [];

  const highPriority =
    improvementPlan?.high_priority || [];

  const mediumPriority =
    improvementPlan?.medium_priority || [];

  const lowPriority =
    improvementPlan?.low_priority || [];

  const strengths =
    safeHealth?.strengths || [];

  const weaknesses =
    safeHealth?.weaknesses || [];

  const formatList = (items) => {
    if (!items || items.length === 0) {
      return "None";
    }

    return items
      .map((item) => {
        if (typeof item === "string") {
          return item;
        }

        return (
          item?.name ||
          item?.skill ||
          item?.keyword ||
          item?.recommendation ||
          item?.description ||
          JSON.stringify(item)
        );
      })
      .join(", ");
  };

  const formatScore = (value) => {
    const number = Number(value);

    if (Number.isNaN(number)) {
      return "0.00";
    }

    return number.toFixed(2);
  };

  const handlePrint = (event) => {
    event.preventDefault();
    event.stopPropagation();

    window.print();
  };

  const handleDownload = async (event) => {
    event.preventDefault();
    event.stopPropagation();

    if (!reportRef.current || downloading) {
      return;
    }

    try {
      setDownloading(true);

      const options = {
        margin: 0.4,
        filename: "AI-Resume-Analysis-Report.pdf",

        image: {
          type: "jpeg",
          quality: 0.98,
        },

        html2canvas: {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: "#ffffff",
        },

        jsPDF: {
          unit: "in",
          format: "a4",
          orientation: "portrait",
        },

        pagebreak: {
          mode: ["css", "legacy"],
        },
      };

      await html2pdf()
        .set(options)
        .from(reportRef.current)
        .save();
    } catch (error) {
      console.error(
        "PDF download error:",
        error
      );

      alert(
        "Unable to download the PDF. Please try again."
      );
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="report-download-wrapper">

      {/* REPORT BUTTONS */}

      <div className="report-actions no-print">

        <button
          type="button"
          className="report-action-button print-button"
          onClick={handlePrint}
        >
          🖨 Print / Save as PDF
        </button>

        <button
          type="button"
          className="report-action-button download-button"
          onClick={handleDownload}
          disabled={downloading}
        >
          {downloading
            ? "Preparing PDF..."
            : "⬇ Download PDF"}
        </button>

      </div>


      {/* PDF REPORT */}

      <div
        ref={reportRef}
        className="resume-report"
      >

        {/* HEADER */}

        <div className="report-header">

          <h1>
            AI Resume Analysis Report
          </h1>

          <p>
            Generated by AI Resume Analyzer
          </p>

        </div>


        {/* SCORE DASHBOARD */}

        <section className="report-section">

          <h2>
            Professional Score Dashboard
          </h2>

          <div className="report-score-grid">

            <div className="report-score-card">
              <strong>
                {formatScore(atsScore)}
              </strong>

              <span>/ 100</span>

              <h3>ATS Score</h3>

              <p>ATS compatibility</p>
            </div>

            <div className="report-score-card">
              <strong>
                {formatScore(jobMatch)}
              </strong>

              <span>/ 100</span>

              <h3>Job Match</h3>

              <p>Job requirement match</p>
            </div>

            <div className="report-score-card">
              <strong>
                {formatScore(resumeHealth)}
              </strong>

              <span>/ 100</span>

              <h3>Resume Health</h3>

              <p>Overall resume quality</p>
            </div>

            <div className="report-score-card">
              <strong>
                {formatScore(contentScore)}
              </strong>

              <span>/ 100</span>

              <h3>Content Score</h3>

              <p>Resume content quality</p>
            </div>

          </div>

        </section>


        {/* JOB SKILL MATCH */}

        <section className="report-section">

          <h2>Job Skill Match</h2>

          <div className="report-stat-grid">

            <div>
              <span>Overall Job Match</span>
              <strong>
                {formatScore(jobMatch)}%
              </strong>
            </div>

            <div>
              <span>Required Matched</span>
              <strong>
                {matchedRequired.length}
              </strong>
            </div>

            <div>
              <span>Required Missing</span>
              <strong>
                {missingRequired.length}
              </strong>
            </div>

            <div>
              <span>Preferred Matched</span>
              <strong>
                {matchedPreferred.length}
              </strong>
            </div>

          </div>

          <h3>✓ Required Skills Matched</h3>

          <p className="report-tags">
            {formatList(matchedRequired)}
          </p>

          <h3>! Required Skills Missing</h3>

          <p className="report-tags">
            {formatList(missingRequired)}
          </p>

          <h3>✓ Preferred Skills Matched</h3>

          <p className="report-tags">
            {formatList(matchedPreferred)}
          </p>

          <h3>! Preferred Skills Missing</h3>

          <p className="report-tags">
            {formatList(missingPreferred)}
          </p>

        </section>


        {/* SKILL GAPS */}

        <section className="report-section">

          <h2>Skills You Can Improve</h2>

          <p className="report-tags">
            {formatList(skillGaps)}
          </p>

        </section>


        {/* ATS KEYWORDS */}

        <section className="report-section">

          <h2>ATS Keyword Analysis</h2>

          <div className="report-stat-grid">

            <div>
              <span>Keyword Match</span>

              <strong>
                {formatScore(
                  keywordAnalysis?.keyword_match_percentage
                )}
                %
              </strong>
            </div>

            <div>
              <span>Total Keywords</span>

              <strong>
                {keywordAnalysis?.total_keywords || 0}
              </strong>
            </div>

            <div>
              <span>Matched</span>

              <strong>
                {matchedKeywords.length}
              </strong>
            </div>

            <div>
              <span>Missing</span>

              <strong>
                {missingKeywords.length}
              </strong>
            </div>

          </div>

          <h3>✓ Matched Keywords</h3>

          <p className="report-tags">
            {formatList(matchedKeywords)}
          </p>

          <h3>! Missing Keywords</h3>

          <p className="report-tags">
            {formatList(missingKeywords)}
          </p>

        </section>


        {/* RESUME QUALITY */}

        <section className="report-section">

          <h2>Resume Quality</h2>

          <div className="report-quality-grid">

            <div>
              <span>Structure</span>

              <strong>
                {resumeQuality?.structure_quality ||
                  "Not available"}
              </strong>
            </div>

            <div>
              <span>Content Score</span>

              <strong>
                {resumeQuality?.content_score ?? 0}
              </strong>
            </div>

            <div>
              <span>Projects</span>

              <strong>
                {resumeQuality?.project_count ?? 0}
              </strong>
            </div>

            <div>
              <span>Resume Lines</span>

              <strong>
                {resumeQuality?.total_lines ?? 0}
              </strong>
            </div>

          </div>

        </section>


        {/* SECTION SCORES */}

        <section className="report-section">

          <h2>
            Section-wise Resume Scores
          </h2>

          <div className="section-score-list">

            {Object.entries(sectionScores).map(
              ([section, score]) => (
                <div
                  className="section-score-row"
                  key={section}
                >
                  <strong>
                    {section.replaceAll("_", " ")}
                  </strong>

                  <span>
                    {formatScore(score)} / 100
                  </span>
                </div>
              )
            )}

          </div>

        </section>


        {/* ROLE ALIGNMENT */}

        <section className="report-section">

          <h2>Job Role Alignment</h2>

          <h3>
            Role Alignment Detected
          </h3>

          <p>
            Detected Role:{" "}
            <strong>
              {result?.detected_role ||
                roleAlignment?.detected_role ||
                roleAlignment?.resume_roles?.[0] ||
                "Software Developer"}
            </strong>
          </p>

        </section>


        {/* RESUME HEALTH */}

        <section className="report-section">

          <h2>Resume Health</h2>

          <h3>
            {formatScore(resumeHealth)} / 100
          </h3>

          <h3>
            {safeHealth?.health_status ||
              "Resume Health"}
          </h3>

          <h3>Strengths</h3>

          <p className="report-tags">
            {formatList(strengths)}
          </p>

          <h3>Weaknesses</h3>

          <p className="report-tags">
            {formatList(weaknesses)}
          </p>

        </section>


        {/* IMPROVEMENT PLAN */}

        <section className="report-section">

          <h2>
            Resume Improvement Recommendations
          </h2>

          <p>
            Focus first on the high-priority
            skill and ATS gaps, then improve
            the remaining resume areas.
          </p>

          {highPriority.length > 0 && (
            <>
              <h3>High Priority</h3>

              {highPriority.map(
                (item, index) => (
                  <div
                    className="recommendation-item"
                    key={`high-${index}`}
                  >
                    <strong>
                      {index + 1}
                    </strong>

                    <p>
                      {typeof item === "string"
                        ? item
                        : item?.recommendation ||
                          item?.description ||
                          JSON.stringify(item)}
                    </p>
                  </div>
                )
              )}
            </>
          )}

          {mediumPriority.length > 0 && (
            <>
              <h3>Medium Priority</h3>

              {mediumPriority.map(
                (item, index) => (
                  <div
                    className="recommendation-item"
                    key={`medium-${index}`}
                  >
                    <strong>
                      {index + 1}
                    </strong>

                    <p>
                      {typeof item === "string"
                        ? item
                        : item?.recommendation ||
                          item?.description ||
                          JSON.stringify(item)}
                    </p>
                  </div>
                )
              )}
            </>
          )}

          {lowPriority.length > 0 && (
            <>
              <h3>Low Priority</h3>

              {lowPriority.map(
                (item, index) => (
                  <div
                    className="recommendation-item"
                    key={`low-${index}`}
                  >
                    <strong>
                      {index + 1}
                    </strong>

                    <p>
                      {typeof item === "string"
                        ? item
                        : item?.recommendation ||
                          item?.description ||
                          JSON.stringify(item)}
                    </p>
                  </div>
                )
              )}
            </>
          )}

        </section>


        {/* BULLET ANALYSIS */}

        <section className="report-section">

          <h2>
            Bullet & Action-Verb Analysis
          </h2>

          <div className="report-stat-grid">

            <div>
              <span>Score</span>

              <strong>
                {formatScore(
                  bulletAnalysis?.score
                )}
              </strong>
            </div>

            <div>
              <span>Total Bullets</span>

              <strong>
                {bulletAnalysis?.total_bullets ?? 0}
              </strong>
            </div>

            <div>
              <span>Strong Action Verbs</span>

              <strong>
                {bulletAnalysis?.action_verb_bullets ?? 0}
              </strong>
            </div>

          </div>

        </section>


        {/* ACHIEVEMENT ANALYSIS */}

        <section className="report-section">

          <h2>
            Achievement & Quantification
          </h2>

          <h3>
            {achievementAnalysis?.status ||
              achievementAnalysis?.achievement_status ||
              "Achievement Analysis"}
          </h3>

          <p>
            Quantified Achievements:{" "}
            <strong>
              {achievementAnalysis?.quantified_count ??
                achievementAnalysis?.quantified_lines?.length ??
                0}
            </strong>
          </p>

          <p>
            Achievement Statements:{" "}
            <strong>
              {achievementAnalysis?.achievement_count ??
                achievementAnalysis?.achievement_lines?.length ??
                0}
            </strong>
          </p>

        </section>


        {/* FINAL SUMMARY */}

        <section className="report-section">

          <h2>Final Resume Summary</h2>

          <h3>
            {safeSummary?.overall_status ||
              "Resume Analysis Summary"}
          </h3>

          <p>
            {safeSummary?.summary ||
              "Resume analysis completed successfully."}
          </p>

        </section>


        {/* FOOTER */}

        <div className="report-footer">
          AI Resume Analyzer • Resume Analysis Report
        </div>

      </div>

    </div>
  );
}

export default ReportDownload;